id = "fozzy"
name = "Fozzy"
version = "0.1.8"
schema_version = 1
authors = ["Matthew Goodman"]
description = "Dark carbon theme with warm earthy syntax colors"
repository = "https://github.com/juxta-tad/fozzy-zed"
